version: "3.4"
services:
  ml_service:
    restart: unless-stopped
    build:
      context: .
    volumes:
      - "~/.config/unity3d/Byte Motion/Ocellus:/mnt/ocellus"
    ports:
      - 0.0.0.0:50055:50055
    shm_size: 1g
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
