version: "3.4"
services:
  ocellus_ml_service:
    restart: always
    build:
      context: .
    volumes:
      - ~/.config/unity3d/Byte\ Motion/Ocellus:/mnt/ocellus 
    ports:
      - 0.0.0.0:50055:50055
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 4G


  # docker run -d --memory="4g"
  #  --memory-swap="4g"
  #  --restart=unless-stopped
  #  --gpus all -p 0.0.0.0:50055:50055 
  #  -v ~/.config/unity3d/Byte\ Motion/Ocellus:/mnt/ocellus 
  #  -it bytemotion/ocellus_ml_service:latest